public enum ErrorCode {

    INVALID_ARGUMENT_FORMAT, INVALID_ARGUMENT_NAME, INVALID_DOUBLE, INVALID_INTEGER,
    MALFORMED_MAP,
    MISSING_DOUBLE, MISSING_INTEGER,
    MISSING_MAP, MISSING_STRING, OK, UNEXPECTED_ARGUMENT

}
